AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Openfinance backend serverless application (root template)

Parameters:
  Runtime:
    Type: String
    Default: nodejs20.x
  MemorySize:
    Type: Number
    Default: 512
  Timeout:
    Type: Number
    Default: 60
  DeploymentBucket:
    Type: String
  DeploymentKeyPrefix:
    Type: String
    Default: deploy-openfinance

Globals:
  Function:
    Runtime: !Ref Runtime
    MemorySize: !Ref MemorySize
    Timeout: !Ref Timeout
    Tracing: Active
    Environment:
      Variables:
        BACKEND_AUDIENCE: '{{resolve:ssm:/openfinance/backend/BACKEND_AUDIENCE}}'
        GOOGLE_CLIENT_ID: '{{resolve:ssm:/openfinance/backend/GOOGLE_CLIENT_ID}}'
        GOOGLE_CLIENT_SECRET: '{{resolve:ssm:/openfinance/backend/GOOGLE_CLIENT_SECRET}}'
        GOOGLE_REDIRECT_URI: '{{resolve:ssm:/openfinance/backend/GOOGLE_REDIRECT_URI}}'
        PLUGGY_CLIENT_ID: '{{resolve:ssm:/openfinance/backend/PLUGGY_CLIENT_ID}}'
        PLUGGY_CLIENT_SECRET: '{{resolve:ssm:/openfinance/backend/PLUGGY_CLIENT_SECRET}}'
        PORT: '{{resolve:ssm:/openfinance/backend/PORT}}'
        PROXY_SIGNING_SECRET: '{{resolve:ssm:/openfinance/backend/PROXY_SIGNING_SECRET}}'
        TURSO_AUTH_TOKEN: '{{resolve:ssm:/openfinance/backend/TURSO_AUTH_TOKEN}}'
        TURSO_DATABASE_URL: '{{resolve:ssm:/openfinance/backend/TURSO_DATABASE_URL}}'
