Resources:
  AccountLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: openfinance-account
      Handler: dist/app/lambda/account-lambda.handler
      CodeUri:
        Bucket: !Ref DeploymentBucket
        Key: !Sub '${DeploymentKeyPrefix}/backend.zip'
      Role: !GetAtt BackendLambdaExecutionRole.Arn
      Tags:
        service: openfinance
        component: backend

  AccountLambdaUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt AccountLambda.Arn
      AuthType: NONE

  AccountLambdaUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref AccountLambda
      Principal: "*"
      FunctionUrlAuthType: NONE
