Resources:
  AccountLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: openfinance-account
      Handler: dist/app/lambda/account-lambda.handler
      CodeUri:
        Bucket: !Ref DeploymentBucket
        Key: !Sub '${DeploymentKeyPrefix}/backend.zip'
      Environment:
        Variables:
          NODE_ENV: production
      Role: !GetAtt BackendLambdaExecutionRole.Arn
      Tags:
        service: openfinance
        component: backend
