CREATE TABLE `transaction` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`date` text NOT NULL,
	`description` text NOT NULL,
	`description_raw` text,
	`type` text NOT NULL,
	`amount` real NOT NULL,
	`amount_in_account_currency` real,
	`balance` real NOT NULL,
	`currency_code` text NOT NULL,
	`category` text,
	`status` text,
	`provider_code` text,
	`payment_data` text,
	`credit_card_metadata` text,
	`merchant` text,
	`category_id` text,
	`operation_type` text,
	`provider_id` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action
);
