CREATE TABLE `investment` (
	`id` text PRIMARY KEY NOT NULL,
	`item_id` text NOT NULL,
	`code` text,
	`issuer_cnpj` text,
	`number` text,
	`isin` text,
	`type` text NOT NULL,
	`subtype` text,
	`status` text,
	`name` text NOT NULL,
	`currency_code` text NOT NULL,
	`date` text,
	`due_date` text,
	`issue_date` text,
	`purchase_date` text,
	`value` real,
	`quantity` real,
	`taxes` real,
	`taxes2` real,
	`balance` real NOT NULL,
	`amount` real,
	`amount_withdrawal` real,
	`amount_profit` real,
	`amount_original` real,
	`issuer` text,
	`rate` real,
	`rate_type` text,
	`fixed_annual_rate` real,
	`last_month_rate` real,
	`annual_rate` real,
	`last_twelve_months_rate` real,
	`owner` text,
	`metadata` text,
	`institution` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON UPDATE no action ON DELETE no action
);
