CREATE TABLE `identity` (
	`id` text PRIMARY KEY NOT NULL,
	`item_id` text NOT NULL,
	`birth_date` text,
	`tax_number` text,
	`document` text,
	`document_type` text,
	`job_title` text,
	`company_name` text,
	`full_name` text,
	`phone_numbers` text,
	`emails` text,
	`addresses` text,
	`relations` text,
	`investor_profile` text,
	`establishment_name` text,
	`establishment_code` text,
	`financial_relationships` text,
	`qualifications` text,
	`social_name` text,
	`sex` text,
	`marital_status` text,
	`nationality` text,
	`other_documents` text,
	`passport` text,
	`incorporation_date` text,
	`parties` text,
	`business_other_documents` text,
	`companies_cnpj` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON UPDATE no action ON DELETE no action
);
