CREATE TABLE `loan` (
	`id` text PRIMARY KEY NOT NULL,
	`item_id` text NOT NULL,
	`contract_number` text,
	`ipoc_code` text,
	`product_name` text NOT NULL,
	`type` text,
	`date` text,
	`contract_date` text,
	`disbursement_dates` text,
	`settlement_date` text,
	`contract_amount` real,
	`currency_code` text NOT NULL,
	`due_date` text,
	`installment_periodicity` text,
	`installment_periodicity_additional_info` text,
	`first_installment_due_date` text,
	`cet` real,
	`amortization_scheduled` text,
	`amortization_scheduled_additional_info` text,
	`cnpj_consignee` text,
	`interest_rates` text,
	`contracted_fees` text,
	`contracted_finance_charges` text,
	`warranties` text,
	`installments` text,
	`payments` text,
	FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON UPDATE no action ON DELETE no action
);
